name: deploy to AWS S3
description: deploy a static website via AWS
inputs: 
  bucket:
    description: 'The S3 bucket name'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-west-1'
  dist-folder:
    description: 'the folder containing the deployable files'
    required: true
runs:
  using: 'node20'
  main: 'main.js'